[[redirects]]
  from = "/scholar/*"
  to ="https://anybarchart-97950e91472a.herokuapp.com/scholar/:splat"
  status = 200
[[redirects]]
  from = "/.well-known/*"
  to = "https://anybarchart-97950e91472a.herokuapp.com/.well-known/:splat"
  status = 200
  for = "/*.yaml"
  [headers.values]
    Content-Type = "text/yaml"
