[[redirects]]
  from = "/scholar/*"
  "https://researchbutler-e010dd4624b1.herokuapp.com/scholar/:splat"
  "https://anybarchart-97950e91472a.herokuapp.com/scholar/:splat"
  status = 200
[[redirects]]
  from = "/.well-known/*"
  "https://researchbutler-e010dd4624b1.herokuapp.com/.well-known/:splat"
  "https://anybarchart-97950e91472a.herokuapp.com/.well-known/:splat"
  status = 200
[[headers]]
  for = "/*.yaml"
